stages:
  - build
  - deploy

build:
  stage: build
  only:
    - main
  image: docker:20.10.16-alpine3.16
  services:
    - name: docker:20.10.16-dind-alpine3.16
      alias: dind
  variables:
    DOCKER_HOST: tcp://dind:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
    - echo "Build successfully!"

deploy:
  stage: deploy
  only:
    - main
  image: kroniak/ssh-client:3.15
  before_script:
    - echo "Deploy to server"
  script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh $SSH_USER@$SSH_HOST docker pull registry.gitlab.com/unimind-kg/unimind-apmf
    - ssh $SSH_USER@$SSH_HOST "docker stop unimind-apmf || true && docker rm unimind-apmf || true"
    - ssh $SSH_USER@$SSH_HOST docker run -p 127.0.0.1:5000:80 \
        -d --name unimind-apmf registry.gitlab.com/unimind-kg/unimind-apmf
